FROM oven/bun:latest AS build

WORKDIR /app

COPY package.json bun.lockb* ./

RUN bun install

COPY . .

RUN bun run build

FROM oven/bun:alpine AS prod

WORKDIR /app

COPY package.json bun.lockb* ./

RUN bun install --production

COPY --from=build /app/dist ./dist

EXPOSE 5000

CMD ["bun", "run", "start"]
